// Generated by CoffeeScript 1.10.0
(function() {
  var Board, Game, GameApplicationService, Player, Position, PossibleActions, PossibleActionsApplicationService;

  Game = require('../domain/game');

  Player = require('../domain/player');

  Board = require('../domain/board');

  PossibleActions = require('../domain/possibleActions');

  Position = require('../domain/position');

  PossibleActionsApplicationService = require('./possibleActionsApplicationService');

  module.exports = GameApplicationService = (function() {
    function GameApplicationService() {}

    GameApplicationService.prototype.createNewGame = function() {
      var board, player1, player2;
      player1 = new Player(1);
      player2 = new Player(2);
      board = new Board();
      return new Game(board, player1, player2);
    };

    GameApplicationService.prototype.getPossibleActions = function(game, x, y) {
      var moves, position, possibleActionsApplicationService, swordAttacks;
      position = new Position(x, y);
      possibleActionsApplicationService = new PossibleActionsApplicationService(game.board, position);
      moves = possibleActionsApplicationService.getMoves();
      swordAttacks = possibleActionsApplicationService.getSwordAttacks();
      return new PossibleActions(moves, swordAttacks);
    };

    return GameApplicationService;

  })();

}).call(this);
