// Generated by CoffeeScript 1.10.0
(function() {
  var Board, Game, GameApplicationService, Player, Position, PossibleTurns, PossibleTurnsApplicationService;

  Game = require('../domain/game');

  Player = require('../domain/player');

  Board = require('../domain/board');

  PossibleTurns = require('../domain/possibleTurns');

  Position = require('../domain/position');

  PossibleTurnsApplicationService = require('./possibleTurnsApplicationService');

  module.exports = GameApplicationService = (function() {
    function GameApplicationService() {}

    GameApplicationService.prototype.createNewGame = function() {
      var board, player1, player2;
      player1 = new Player(1);
      player2 = new Player(2);
      board = new Board();
      return new Game(board, player1, player2);
    };

    GameApplicationService.prototype.getPossibleActions = function(game, x, y) {
      var moves, position, possibleTurnsApplicationService, swordAttacks;
      position = new Position(x, y);
      possibleTurnsApplicationService = new PossibleTurnsApplicationService(game.board, position);
      moves = possibleTurnsApplicationService.getMoves();
      swordAttacks = possibleTurnsApplicationService.getSwordAttacks();
      return new PossibleTurns(moves, swordAttacks);
    };

    return GameApplicationService;

  })();

}).call(this);
