// Generated by CoffeeScript 1.10.0
(function() {
  var Board;

  module.exports = Board = (function() {
    function Board() {
      this.gameTokens = [];
    }

    return Board;

  })();

}).call(this);
