// Generated by CoffeeScript 1.10.0
(function() {
  var Board;

  module.exports = Board = (function() {
    function Board() {
      this.tiles = (function() {
        var i, results;
        results = [];
        for (i = 0; i <= 6; i++) {
          results.push((function() {
            var j, results1;
            results1 = [];
            for (j = 0; j <= 5; j++) {
              results1.push(null);
            }
            return results1;
          })());
        }
        return results;
      })();
    }

    return Board;

  })();

}).call(this);
