// Generated by CoffeeScript 1.10.0
(function() {
  var GameToken, Weapon;

  Weapon = require('./weapon');

  module.exports = GameToken = (function() {
    function GameToken(playerId) {
      this.playerId = playerId;
      this.health = 10;
      this.isAlive = true;
      this.sides = [
        {
          isReady: true,
          weapon: Weapon.shield
        }, {
          isReady: true,
          weapon: Weapon.sword
        }, {
          isReady: true,
          weapon: Weapon.arrow
        }, {
          isReady: true,
          weapon: null
        }, {
          isReady: true,
          weapon: Weapon.sword
        }, {
          isReady: true,
          weapon: Weapon.arrow
        }
      ];
      this.possibleActions = {
        moves: [],
        swordAttacks: [],
        arrowAttacks: []
      };
    }

    return GameToken;

  })();

}).call(this);
