// Generated by CoffeeScript 1.10.0
(function() {
  var Game, Position;

  Position = require('./position');

  module.exports = Game = (function() {
    function Game(board, player1, player2) {
      this.board = board;
      this.players = [player1, player2];
      this.createdAt = new Date;
      this.gameState = {
        activePlayer: 0,
        remainingPlayerTurns: 6
      };
      this._placeTokens();
    }

    Game.prototype._placeTokens = function() {
      var gameToken, i, j, k, len, player, ref, results;
      ref = this.players;
      results = [];
      for (i = k = 0, len = ref.length; k < len; i = ++k) {
        player = ref[i];
        results.push((function() {
          var l, len1, ref1, results1;
          ref1 = player.gameTokens;
          results1 = [];
          for (j = l = 0, len1 = ref1.length; l < len1; j = ++l) {
            gameToken = ref1[j];
            gameToken.id = (i * player.gameTokens.length) + j;
            gameToken.playerId = i;
            if (i === 0) {
              gameToken.position = new Position(0, j);
            } else {
              gameToken.position = new Position(5, j);
            }
            results1.push(this.board.gameTokens.push(gameToken));
          }
          return results1;
        }).call(this));
      }
      return results;
    };

    return Game;

  })();

}).call(this);
