// Generated by CoffeeScript 1.10.0
(function() {
  var Board, Game, GameApplicationService, Player, Position, PossibleTurns;

  Game = require('./game');

  Player = require('./player');

  Board = require('./board');

  PossibleTurns = require('./possibleTurns');

  Position = require('./position');

  module.exports = GameApplicationService = (function() {
    function GameApplicationService() {}

    GameApplicationService.prototype.createNewGame = function() {
      var board, player1, player2;
      player1 = new Player(1);
      player2 = new Player(2);
      board = new Board();
      return new Game(board, player1, player2);
    };

    GameApplicationService.prototype.getPossibleActions = function(game, x, y) {
      var position, possibleTurns, possibleTurnsDto;
      position = new Position(x, y);
      possibleTurns = new PossibleTurns(game.board, position);
      possibleTurnsDto = {};
      possibleTurnsDto.moves = possibleTurns.getMoves();
      possibleTurnsDto.swordAttacks = possibleTurns.getSwordAttacks();
      return possibleTurnsDto;
    };

    return GameApplicationService;

  })();

}).call(this);
