// Generated by CoffeeScript 1.10.0
(function() {
  var Board, Game, GameApplicationService, Player;

  Game = require('./game');

  Player = require('./player');

  Board = require('./board');

  module.exports = GameApplicationService = (function() {
    function GameApplicationService() {}

    GameApplicationService.prototype.createNewGame = function() {
      var board, player1, player2;
      player1 = new Player(1);
      player2 = new Player(2);
      board = new Board();
      return new Game(board, player1, player2);
    };

    return GameApplicationService;

  })();

}).call(this);
