// Generated by CoffeeScript 1.10.0
(function() {
  var GameToken, Player;

  GameToken = require('./gametoken');

  module.exports = Player = (function() {
    function Player(id) {
      this.id = id;
      this.actionPoints = 6;
      this.gameTokens = (function() {
        var i, results;
        results = [];
        for (i = 1; i <= 6; i++) {
          results.push(new GameToken(this.id));
        }
        return results;
      }).call(this);
    }

    return Player;

  })();

}).call(this);
