// Generated by CoffeeScript 1.10.0
(function() {
  var Position;

  module.exports = Position = (function() {
    function Position(x, y) {
      this.x = x;
      this.y = y;
    }

    return Position;

  })();

}).call(this);
