// Generated by CoffeeScript 1.10.0
(function() {
  var PossibleActions;

  module.exports = PossibleActions = (function() {
    function PossibleActions(moves, swordAttacks, arrowAttacks) {
      this.moves = moves;
      this.swordAttacks = swordAttacks;
      this.arrowAttacks = arrowAttacks;
    }

    return PossibleActions;

  })();

}).call(this);
