// Generated by CoffeeScript 1.10.0
(function() {
  var Position, PossibleTurns;

  Position = require('./position');

  module.exports = PossibleTurns = (function() {
    function PossibleTurns(board, position) {
      this.board = board;
      this.x = position.x;
      this.y = position.y;
    }

    PossibleTurns.prototype.getMoves = function() {
      if (this.board.tiles[this.x][this.y] != null) {
        return this.getNeighbours(this.position);
      } else {
        return [];
      }
    };

    PossibleTurns.prototype.getNeighbours = function(position) {
      return [new Position(this.x, this.y - 1), new Position(this.x + 1, this.y - (this.x % 2 === 0 ? 1 : 0)), new Position(this.x + 1, this.y + (this.x % 2 === 0 ? 0 : 1)), new Position(this.x, this.y + 1), new Position(this.x - 1, this.y + (this.x % 2 === 0 ? 0 : 1)), new Position(this.x - 1, this.y - (this.x % 2 === 0 ? 1 : 0))];
    };

    PossibleTurns.prototype.isFieldInsideBounds = function(position) {
      var ref, ref1;
      if ((0 <= (ref = this.x) && ref <= 6) && (0 <= (ref1 = this.y) && ref1 <= 5)) {
        return true;
      } else {
        return false;
      }
    };

    return PossibleTurns;

  })();

}).call(this);
