// Generated by CoffeeScript 1.10.0
(function() {
  var PossibleTurns;

  module.exports = PossibleTurns = (function() {
    function PossibleTurns(moves, swordAttacks) {
      this.moves = moves;
      this.swordAttacks = swordAttacks;
    }

    return PossibleTurns;

  })();

}).call(this);
