// Generated by CoffeeScript 1.10.0
(function() {
  var GameToken, Weapon;

  Weapon = require('../src/weapon');

  module.exports = GameToken = (function() {
    function GameToken(playerId, position) {
      this.playerId = playerId;
      this.position = position;
      this.health = 10;
      this.sides = [Weapon.shield, Weapon.sword, Weapon.arrow, Weapon.shield, Weapon.sword, Weapon.arrow];
    }

    return GameToken;

  })();

}).call(this);
