// Generated by CoffeeScript 1.10.0
(function() {
  var GameApplicationService, exports, gameApplicationService;

  GameApplicationService = require('./application/gameApplicationService');

  gameApplicationService = new GameApplicationService();

  module.exports = exports = {
    createNewGame: function() {
      return gameApplicationService.createNewGame();
    },
    getPossibleActions: function(game, x, y) {
      return gameApplicationService.getPossibleActions(game, x, y);
    },
    move: function(game, tokenId, position) {
      return gameApplicationService.move(game, tokenId, position);
    },
    attack: function(game, attackerTokenId, targetTokenId) {
      return gameApplicationService.attack(game, attackerTokenId, targetTokenId);
    }
  };

}).call(this);
