// Generated by CoffeeScript 1.10.0
(function() {
  var GameApplicationService, gameApplicationService;

  GameApplicationService = require('./domain/gameApplicationService');

  gameApplicationService = new GameApplicationService();

  module.exports = {
    createNewGame: function() {
      return gameApplicationService.createNewGame();
    }
  };

}).call(this);
