// Generated by CoffeeScript 1.10.0
(function() {
  var Player;

  module.exports = Player = (function() {
    Player.prototype.actionPoints = 6;

    function Player(id, color) {
      this.id = id;
      this.color = color;
    }

    return Player;

  })();

}).call(this);
