// Generated by CoffeeScript 1.10.0
(function() {
  var Point;

  module.exports = Point = (function() {
    function Point(x, y) {
      this.x = x;
      this.y = y;
    }

    return Point;

  })();

}).call(this);
